// <auto-generated />
namespace QueroTrocarMeuLivro.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Inicio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inicio));
        
        string IMigrationMetadata.Id
        {
            get { return "201301260053178_Inicio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
